set nocompatible

filetype off

set runtimepath^=html5.vim
set runtimepath^=vader.vim
set runtimepath^=vim-javascript
set runtimepath^=.

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

filetype plugin indent on
syntax enable
